const players = {
    "data": [
        {
            "id": {
                "gameId": 1992020726,
                "skaterId": 8444945
            },
            "activePlayer": 0,
            "ageInDaysForYear": 143,
            "ageInYears": 32,
            "careerAssists": 601,
            "careerGoals": 498,
            "careerPoints": 1099,
            "gameDate": "1993-02-22T00:00:00",
            "gameId": 1992020726,
            "goalieFirstName": "Kirk",
            "goalieId": 8449474,
            "goalieLastName": "McLean",
            "homeScore": 1,
            "homeTeamId": 23,
            "homeTriCode": "VAN",
            "seasonId": 19921993,
            "skaterCareerGamesPlayed": 1129,
            "skaterFirstName": "Glenn",
            "skaterGamesPlayed": 954,
            "skaterId": 8444945,
            "skaterLastName": "Anderson",
            "skaterTeamId": 10,
            "skaterTeamName": "Toronto Maple Leafs",
            "typeOfPoint": "G",
            "visitorScore": 8,
            "visitorTeamId": 10,
            "visitorTriCode": "TOR"
        },
        {
            "id": {
                "gameId": 1995021020,
                "skaterId": 8445000
            },
            "activePlayer": 0,
            "ageInDaysForYear": 191,
            "ageInYears": 32,
            "careerAssists": 698,
            "careerGoals": 640,
            "careerPoints": 1338,
            "gameDate": "1996-04-07T00:00:00",
            "gameId": 1995021020,
            "goalieFirstName": "Mike",
            "goalieId": 8450833,
            "goalieLastName": "Richter",
            "homeScore": 4,
            "homeTeamId": 1,
            "homeTriCode": "NJD",
            "seasonId": 19951996,
            "skaterCareerGamesPlayed": 1639,
            "skaterFirstName": "Dave",
            "skaterGamesPlayed": 998,
            "skaterId": 8445000,
            "skaterLastName": "Andreychuk",
            "skaterTeamId": 1,
            "skaterTeamName": "New Jersey Devils",
            "typeOfPoint": "G",
            "visitorScore": 2,
            "visitorTeamId": 3,
            "visitorTriCode": "NYR"
        },
        {
            "id": {
                "gameId": 1972020112,
                "skaterId": 8445240
            },
            "activePlayer": 0,
            "ageInDaysForYear": 181,
            "ageInYears": 37,
            "careerAssists": 813,
            "careerGoals": 556,
            "careerPoints": 1369,
            "gameDate": "1972-11-09T00:00:00",
            "gameId": 1972020112,
            "goalieFirstName": "Denis",
            "goalieId": 8449866,
            "goalieLastName": "DeJordy",
            "homeScore": 8,
            "homeTeamId": 6,
            "homeTriCode": "BOS",
            "seasonId": 19721973,
            "skaterCareerGamesPlayed": 1540,
            "skaterFirstName": "Johnny",
            "skaterGamesPlayed": 1144,
            "skaterId": 8445240,
            "skaterLastName": "Bucyk",
            "skaterTeamId": 6,
            "skaterTeamName": "Boston Bruins",
            "typeOfPoint": "G",
            "visitorScore": 3,
            "visitorTeamId": 17,
            "visitorTriCode": "DET"
        },
    ]
}

export default players;